<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIPNw4RZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIPNw4RZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIPNw4RZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIPNw4RZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIPNw4RZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'IPNw4RZ',
    'container.build_id' => '85dd5bd9',
    'container.build_time' => 1580576988,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIPNw4RZ');
