<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUyxwcLP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUyxwcLP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUyxwcLP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUyxwcLP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUyxwcLP\App_KernelDevDebugContainer([
    'container.build_hash' => 'UyxwcLP',
    'container.build_id' => '0a8cd2ba',
    'container.build_time' => 1580725124,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUyxwcLP');
